### ISSUE TITLE
Camera disconnects when monitor is off

### ISSUE THREAD

**Issue by shahlab-ucla** [Gordon999/RPiCamGUI#10]
Thanks for your awesome utility! We're trying to use your GUI for running timelapses on an array of Raspberry Pi's with the cameras mounted to microscopes for a research project. To simplify control, we have all of the Pi's on a KVM switch but we've found that switching between Pi's causes timelapses to fail because the camera can no longer be found. Does this sound like something that would be easy to fix? I have no experience with the Pi camera API so figured it would be easiest to ask you.

**Comment by shahlab-ucla** [comment]
The Pi isn't on a network I can post a screenshot from so I snapped a pic of the console output:
![PXL_20240320_163304710](https://github.com/Gordon999/RPiCamGUI/assets/67645685/4d416fd7-fb87-4797-824e-dba1fdcf8ed0)

**Comment by shahlab-ucla** [comment]
Just tested the force_hotplug and it worked! Thanks a ton!

**Comment by Gordon999** [comment]
Glad it's sorted.
