### ISSUE TITLE
Arducam 64mp Hawkeye cam on Pi4 latest Bookworm

### ISSUE THREAD

**Issue by fridayghost** [Gordon999/RPiCamGUI#12]
This is the error i receive when i run the python script.

```
pygame 2.1.2 (SDL 2.26.5, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Pi: 4
Camera: imx290
No Camera Found
```

This is the content of the libcams.txt 
```
Available cameras
-----------------
0 : arducam_64mp [9248x6944 10-bit RGGB] (/base/soc/i2c0mux/i2c@1/arducam_64mp@1a)
    Modes: 'SRGGB10_CSI2P' : 1280x720 [120.09 fps - (2064, 2032)/5120x2880 crop]
                             1920x1080 [60.04 fps - (784, 1312)/7680x4320 crop]
                             2312x1736 [30.00 fps - (0, 0)/9248x6944 crop]
                             3840x2160 [20.00 fps - (784, 1312)/7680x4320 crop]
                             4624x3472 [10.00 fps - (0, 0)/9248x6944 crop]
                             8000x6000 [3.00 fps - (624, 472)/9248x6944 crop]
                             9152x6944 [2.70 fps - (0, 0)/9248x6944 crop]
```

**Comment by fridayghost** [comment]
Changing 'arduc' to 'arduca' didn't work.

But, changing it to 'arducam_64mp' worked.
Thank you.

**Comment by Gordon999** [comment]
I am pleased to hear you have resolved it but l can't understand how !

It only reads the first 6 chars of the camera name. So it should only match with arduca.

Did you change any other of the code ? Eg cam0 = camstxt[x][4:10]

**Comment by fridayghost** [comment]
Ah yes, I forgot.
I did edit the file and change the line

`cam0 = camstxt[x][4:10]`
to
`cam0 = arducam_64mp`

I apologize for the confusion. Thank a lot again for the support and this awesome script.

**Comment by Gordon999** [comment]
V5.15 has a couple of fixes, l now have a arducam 64mp hawkeye to test.

**Comment by fridayghost** [comment]
Thank you.
