### ISSUE TITLE
Long Delay for Stills on Pi4

### ISSUE THREAD

**Issue by Vacant0mens** [Gordon999/RPiCamGUI#13]
Running this on a Pi4 with a 1080p screen, I click 'Capture' and it sits there for 5-10 seconds before it actually takes the picture with just a "Please wait" at the top of the preview. I don't have a tripod, so such a long delay makes it hard to get a good picture.

Is there a setting I need to change or a feature I can disable to make it take pictures more quickly? Or is this a limitation of the way that the script is made and/or an issue with its dependencies?

**Comment by Gordon999** [comment]
Which  camera are you using ?

**Comment by Vacant0mens** [comment]
By default, the "Duration" is already set to `00:10:00`. But when I click `CAPTURE Timelapse`, the preview stops on the last thing the camera picked up, and the `CAPTURE Still` gets greyed out.

I'm using the official RPi HQ camera with no autofocus.

**Comment by Vacant0mens** [comment]
I also tried the same process in fullscreen mode, just for fun.
It minimizes the main window when the new pop-up preview window shows up, and the pop-up preview window uses default settings for resolution and window size, so the pop-up window is small, and it doesn't have the UI buttons or anything in it, just the image preview. Is this the regular `rpicam-hello` preview window?

**Comment by Gordon999** [comment]
The script doesn't normally use the rpicam-vid preview, it captures frames from rpicam-vid running in a sub-process 
and shows them in a pygame frame. This allows me to add the gridlines, keys, histogram etc. I didn't find a way of adding these to a rpicam or picamera2 preview screens.
The advantage of picamera2 is it would allow the changing of camera parameters without restarting the subprocess and
 awaiting the preview, as I do in https://github.com/Gordon999/PiVideoer2. I may move to picamera2 at some stage but
 not sure it would be easy to achieve all the options easily.
Thanks for pointing out the issue with fullscreen. I have disabled the preview if you select fullscreen, which means you
 can't  see the camera output. I also notice the keys are corrupted which needs investigating, it used to work OK.
The reason the normal preview freezes when you select timelapse is it stops the subprocess and starts rpicam-still
 with the -s option, awaiting a trigger to capture. I can't capture frames in that mode and put them in the pygame frame.
 
I have added a key STILL -t which allows you to set the -t option which set the time before a photo is taken, by default
 this would be 5 seconds, reducing it will speed the capture time BUT may not allow the camera to settle.

Some amendments made it v5.28

**Comment by Gordon999** [comment]
In v5.29 l have added the option to use an external button/switch between gpio 12 and gnd to trigger a still Capture once you have started the Timelapse, as an alternative to clicking on the on screen CAPTURE still button.

**Comment by Gordon999** [comment]
I think l have completed what l can to resolve the issue you raised, within the structure of the code.
 Let me know if you still have any issues.

**Comment by Gordon999** [comment]
Assumed completed

**Comment by Vacant0mens** [comment]
Would you mind summarizing your last few changes?
I can read the code in the dif's just fine, but there's so much going on, it's hard to know how those changes help the issues I was having...

**Comment by Gordon999** [comment]
Relevant to your issue:

- CAPTURE Still onscreen key now not greyed out when TIMELAPSE started (assuming in NORMAL mode).
- External button/switch on GPIO12 now active when TIMELAPSE started (assuming in NORMAL mode) to capture STILLs.
- Onscreen keys fixed in FULLSCREEN Mode.
- Key added to allow rpicam -t parameter to be varied, allowing shorter capture times.

Other:

- Larger range allowed for Timelapse interval
- Arducam 16MP re-activated (disabled after I had a failed camera, whilst I checked).
- With Arducam 16MP/64MP you now need to use their installation. Now uses --lens-position option.
- rpicam-vid --rawfull parameter removed now its obselete.
- Code related to Max Video Format tidied up (now a def).
- Some Video guide lines added / improved.
- Name of config file changed, due to extra parameter (timet) added.
