### ISSUE TITLE
support for other cameras like imx585 imx293 imx294

### ISSUE THREAD

**Issue by VoeGalore** [Gordon999/RPiCamGUI#14]
Hi,
Great project, I used it with HQ camera and pi 4 for microscopes at work.

I have a camera module based on IMX585 https://github.com/will127534/StarlightEye 
Installed the driver per instructions in the git referenced above and rpicam operations works. I couldn't get it to work with RPiCamGUI tho. A simple message "camera not found"

Could you provide some instructions or guidance to adapting to this sensor? The author also has driver for modules based on IMX294 & IMX293 sensors.

**Comment by Gordon999** [comment]
If you run rpicam-vid --list-cameras what does it say ?

**Comment by VoeGalore** [comment]
```
$ rpicam-vid --list-cameras
Available cameras
-----------------
0 : imx585 [3840x2160 16-bit RGGB] (/base/axi/pcie@120000/rp1/i2c@80000/imx585@1A)
    Modes: 'SRGGB12_CSI2P' : 1928x1090 [87.60 fps - (0, 0)/3840x2160 crop]
                             3856x2180 [43.80 fps - (0, 0)/3840x2160 crop]
           'SRGGB16' : 1928x1090 [30.00 fps - (0, 0)/3840x2160 crop]
                       3856x2180 [21.90 fps - (0, 0)/3840x2160 crop]

$ python3 ~/RPiCamGUI.py
pygame 2.1.2 (SDL 2.26.5, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Pi: 5
No Camera Found
$ 
~~~

RPi OS Bookworm 64bit, default desktop installation. Camera is hooked up to default cam1 interface.

**Comment by Gordon999** [comment]
Thanks , l'll look at adding it

**Comment by Gordon999** [comment]
Please try v5.33. I don't know all the parameters for those sensors.
Let me know any issues.

**Comment by VoeGalore** [comment]
Hi, 
Thanks for the fast fix. I can capture full-res stills in any desired format, which fulfills the most important function.
The IMX585 module has a 16:9 sensor, I couldn't get the preview to output 16:9 aspect ratio (preview locks to 4:3 and crops sides). In addition, when using Zoom button to show histogram and focus meter, certain zoom levels show distorted image (likely scaling 16:9 frame to 4:3 preview region).

Is there a way to draw the control buttons below the preview frame? since the sensor is 16:9, and I happen to have 4:3 1600x1200 (and 5:4 1280x1024) monitors at hand.

**Comment by Gordon999** [comment]
Try v5.34.

If you want the buttons at the bottom try setting sq_dis = 1 in line 57. This may not be what you want but it would be a lot of work to change it.

Regards the imx585 what is the maximum exposure time?

Regards the imx293 & imx294 can you do a rpicam-vid --list-cameras for them ?

Thanks

**Comment by VoeGalore** [comment]
> Regards the imx585 what is the maximum exposure time?
According to Will the author of the driver, max 65535 seconds, 



> Does it have a ir filter switch, how is it switched , a gpio ?
I couldn't get my IR filter to work properly, but here's the documentation [https://github.com/will127534/StarlightEye/blob/main/software/README.md](url)



> Regards the imx293 & imx294 can you do a rpicam-vid --list-cameras for them ?
I don't have these two camera modules on hand, I asked cause the author wrote the drivers for all 3 in a project. I plan to get imx294 but not sure when availability will be.

I tested v5.34, yes square display option makes use of the screen better, but there's a big blank banner below the preview frame (it is 16:9 now!).
Also I tried autorun it by creating systemd service, but by default service always exit on error 1. There are a lot of gpio related messages in the console output. Is this due to stubs for imx293/4 ?

**Comment by Gordon999** [comment]
Try v5.35, set alt_dis = 2 if using a 16x9 camera.

To autostart add

@/usr/bin/python3 /home/USERNAME/RPiCamGUI.py

( change USERNAME to your log in name)

To /etc/xdg/lxsession/LXDE-pi/autostart

If using bookworm you may need to use X11 instead of wayland

**Comment by VoeGalore** [comment]
thanks, works well sofar!
I don't use desktop so running systemd service for now, had to manually specify the folders in the python script and comment out the login check. looks much better now!

the performance appears to be worse than directly running rpicam-still. is this issue inherent to python? I'm looking for places where I can turn off unnecessary functions (I only need stills, no stream or video required)

**Comment by Gordon999** [comment]
In what areas is the performance worse ?

**Comment by VoeGalore** [comment]
It's the preview port that gives me the feeling of sluggishness. When I run a simple rpicam-still command I get 60fps smooth preview which is beneficial to my microscopy work (also responds to exposure changes and frame movements swiftly). While in RPiCamGUI preview, there's likely 15FPS or less. I assume it's due to the encoded H264 stream causing slowdown but same if I change to raw video format, and I personally do not need video mode. I use an M.2 SSD as main disk (Argon NEO 5 RPi 5 case)

The 5s delay in capturing still does not really bother me but I will try the config change, thanks!

**Comment by Gordon999** [comment]
under # initial parameters try changing 'prev_fps   = 10' to a larger number

**Comment by Gordon999** [comment]
Do you mean imx283 ? I can't find any details on a imx293, and driver on the site you linked seems to be a 283.

**Comment by VoeGalore** [comment]
> Do you mean imx283 ? I can't find any details on a imx293, and driver on the site you linked seems to be a 283.

Yes IMX283, that was a terrible typo from me, sorry! I have the IMX283 module installed and tested with regular rpicam-apps without issue.

**Comment by Gordon999** [comment]
Can you show me the output from rpicam-vid --list-cameras

**Comment by grching** [comment]
Just picked up the AI camera. 
Running with v5.41 it appears that IMX500 is not supported.


rpicam-hello --list-camera
Available cameras
-----------------
0 : imx500 [4056x3040 10-bit RGGB] (/base/axi/pcie@120000/rp1/i2c@88000/imx500@1a)
    Modes: 'SRGGB10_CSI2P' : 2028x1520 [30.02 fps - (0, 0)/4056x3040 crop]
                             4056x3040 [10.00 fps - (0, 0)/4056x3040 crop]


**output:** python3 ~/RPiCamGUI.py
pygame 2.1.2 (SDL 2.26.5, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Pi: 5
No Camera Found: -1  cam0:  imx500

**added:**
    if Pi_Cam != -1:
        print("Camera:",cameras[Pi_Cam])
    else:
        print("No Camera Found:", Pi_Cam, " cam0: ", cam0)
        pygame.display.quit()
        sys.exit()

**Comment by grching** [comment]
@Gordon999 Thank you for the quick response. Changed it and it appears to be working. Much better then my hack of adding 'imx500' to the end of the array and guessing at the other values to add to the other arrays. 

Have a good holiday! Hopefully you have as good a holiday as I had when I went to Spiel Essen earlier this year.
