### ISSUE TITLE
Using RealVNC with RPiCamGUI

### ISSUE THREAD

**Issue by Swebbee** [Gordon999/RPiCamGUI#3]
Hi, 
I used the original app and it was excellent thank you.

Using the new app I am unable to initiate viewer using RealVNC as pygame exits with No available displays.
Is there something in the config script I can change for it to work? or is it a bigger issue.
I am using the latest OS for the RPI with a 3b.

Regards
Sean

**Comment by Gordon999** [comment]
Sorry l have never used realvnc.
By original app do you mean PilibcameraGUI ?
Both apps work similarly. Did you use Bullseye and now bookworm ?
If bookworm have you tried X11 rather than wayland ?

**Comment by Gordon999** [comment]
assumed resolved

**Comment by Swebbee** [comment]
Went back to Bullseye, works fine.

Thanks
Sean
