### ISSUE TITLE
IMX519 on bookworm RPi4

### ISSUE THREAD

**Issue by pixaren** [Gordon999/RPiCamGUI#5]
RPI 4

Gives me:

pixar@raspberrypi:~ $ python3 /RPiCamGUI.py
pygame 2.1.2 (SDL 2.26.5, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
4
Traceback (most recent call last):
File "/home/pixar/RPiCamGUI.py", line 460, in
Camera_Version()
File "/home/pixar/RPiCamGUI.py", line 315, in Camera_Version
vfps2.append(int(forms[q][1:3]))
^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '9.'
pixar@raspberrypi: $

Any suggestion how to solve this?

**Comment by Gordon999** [comment]
Can you show me the contents of libcams.txt.

**Comment by pixaren** [comment]
I'm sorry, i'm new at this, where are the file libcams.txt located?

**Comment by Gordon999** [comment]
Probably /home/pixar/

**Comment by Gordon999** [comment]
Try changing line 315
 from
 vfps2.append(int(forms[q][1:3]))
To
vfps2.append(int(float(forms[q][1:3])))

And l'll test it tomorrow...

**Comment by Gordon999** [comment]
should be fixed in v4.89

**Comment by pixaren** [comment]
Thank you very much. It works now!

**Comment by Gordon999** [comment]
Closed
