### ISSUE TITLE
Camera_Version() Value Error

### ISSUE THREAD

**Issue by andrsuth** [Gordon999/RPiCamGUI#6]
Testing Pi5 with Arducam 16MP (B0371) 

I receive...
File "home/andrsuth/RPICamGUI.py", line 315, in Camera Version
vfps2.append(int(forms[q][1:3])) 
ValueError: invalid literal for int() with base 10: '9.'

**Comment by Gordon999** [comment]
Just fixed try v4.89

**Comment by andrsuth** [comment]
Working!  Thank you for a great tool (and such a rapid turnaround on an issue!)

**Comment by Gordon999** [comment]
Thanks. Someone reported the same issue yesterday so l had worked the fix just as you reported it.
