### ISSUE TITLE
Manual focus jumps back and forth

### ISSUE THREAD

**Issue by pixaren** [Gordon999/RPiCamGUI#8]
When i use libcamera and specify a lens position value (for focusing) it works good, but in the RPiCamGUI, the focus doesn't wanna stick to the focus value i choose and keep jumping back and forth and try focusing even in manual mode (which doesn't work in darkness)
Is it possible to implement the libcamera lens position in RPiCamGUI?
Or do i do something wrong?

**Comment by Gordon999** [comment]
Which camera are you using ?
Which Pi are you using ?

**Comment by pixaren** [comment]
Yes, Arducams IMX519 on a RPI 4

**Comment by Gordon999** [comment]
OK. That's the issue. Unless you use the proprietary Arducam libcamera, which you can't with RPiCamGUI but can with PiLibcameraGUI, you  can't get their autofocus with  Pi4. I use an autofocus algorithm in python on the Pi4 which is slow. It will read a value for focus and if below a certain value will keep trying which l assume is your case. If you use a Pi5 you can install Arducams json so that works OK.

When you use aurtofocus what values does it show for focus in the top left corner ?

**Comment by Gordon999** [comment]
v4.90 will stop the af running continuously if it cant focus.
Note it focuses using the red square that is on the screen whilst focussing

**Comment by Gordon999** [comment]
Please try RPiCamGUIard.py and let me know any issues

**Comment by pixaren** [comment]
The RPiCamGUIard.py seems to be working with the focus, now it not jumping back and forth, but when i shift the focuspoint and set the focus to another object, it shifts on the screen but the photo is still on the old point, i will check it more exactly tomorrow.

**Comment by Gordon999** [comment]
With the arducam moving the red box only moves the measuring point for focus value and the histogram ( if zoomed). I haven't checked if l can use windowed auto focus (spot) with the arducam.

**Comment by Gordon999** [comment]
Please try v4.94 of RPiCAMGUIard. To enable spot focus set in Auto or Continuous focus and click where required on the image

**Comment by pixaren** [comment]
Tried the 4.94 now, but the focus keeps focusing in the middle of the screen when i take a photo, tried the spot focus, manual, changed values is manual, it still changes on the screen as it should, but when i fires the photo trigger, the photo have the focus locked in the middle of the screen, always.

**Comment by Gordon999** [comment]
Sorry, l haven't updated the taking parts of the code yet !! At least the preview proves it works .

**Comment by Gordon999** [comment]
Hopefully fixed

**Comment by Gordon999** [comment]
Assumed fixed

**Comment by pixaren** [comment]
I tried both but the problem persist.

**Comment by Gordon999** [comment]
Are you using the arducam libcamera apps ?

Is your rpi os upto date ?

**Comment by Gordon999** [comment]
I am not sure l can do anything else, l believe this is fixed.
Let me know if you have issues.
