### ISSUE TITLE
Any way to use CamGUI just using a preview screen with VNC?

### ISSUE THREAD

**Issue by dmiles512** [Gordon999/RPiCamGUI#9]
This is not really an "issue" as it is working as intended for me.

I am using a Pi Zero 2 mounted inside a 3D printer with a PiCam module 3 wide. When I run RPiCamGUI it informs me that it can not run, because it can not find an external monitor, which I assume is the way it's supposed to work.

Is there a way the code can be modified so that I can run this configuration using a preview window with VNC? If not that's fine, I can always take it out of its case, and attach a small monitor. That should allow me to get it close enough. Just thought I'd ask. Great work, by the way, really finding it useful in setting up PiCams.

**Comment by Gordon999** [comment]
Sorry l have never used VNC. Is it the fact there is no physical monitor attached or the use of pygame etc ?
If using bookworm is there any difference using Wayland or X11?

**Comment by Gordon999** [comment]
The code doesn't check for a monitor.

**Comment by Gordon999** [comment]
Could this be due to this issue ?

https://github.com/Gordon999/RPiCamGUI/issues/10

**Comment by dmiles512** [comment]
It very well could be. I have been away from home all week, but I would
look forward to looking into this a little further this weekend.

Thanks for the follow up, and a great utility. It was just what I was
 looking for.

**Comment by Gordon999** [comment]
Assumed resolved
